version: '3.9'

services:
  backend:
    build:
      context: ./backend  # 指向你的後端應用程式的目錄
      dockerfile: Dockerfile  # 默認為 Dockerfile，這裡可以省略
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network  # 指定內部網路

  frontend:
    build:
      context: ./frontend  # 指向你的前端應用程式的目錄
      dockerfile: Dockerfile  # 默認為 Dockerfile，這裡可以省略
    ports:
      - "3000:80"  # 將本地的 3000 埠映射到容器內的 80 埠
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend  # 後端的內部服務名稱
    networks:
      - app-network  # 指定內部網路

networks:
  app-network:
    driver: bridge  # 預設 Docker 網路模式
