version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - BACKEND_SERVICE_ENDPOINT=http://localhost:5000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - BACKEND_SERVICE_ENDPOINT=http://backend:5000 # 本地測試
      # 在雲端上，可以通過 task 定義或其他方法設置此變數

networks:
  app-network:
    driver: bridge
